# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/jekyll
image: ruby:2.3

stages:
- test
- deploy

pages-build-test:
  stage: test
  script:
  - gem install bundler
  - bundle install
  - rm _posts/*
  - cp _testposts/*.md _posts/
  - jekyll build -d test
#  artifacts:
#    paths:
#    - test
  only:
  - master

pages:
  stage: deploy
  script:
  - gem install bundler
  - bundle install
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master

pages-signal-log:
  stage: deploy
  script:
  - cd signal-log
  - gem install bundler
  - bundle install
  - jekyll build -d public/signal-log
  artifacts:
    paths:
    - public/signal-log
  only:
  - master
