# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/jekyll
image: ruby:2.3

#test:
#  stage: test
#  script:
#  - gem install jekyll
#  - jekyll build -d test
#  artifacts:
#    paths:
#    - test
#  except:
#  - master

pages:
  stage: deploy
  script:
  - gem install bundler
  - bundle install
#  - gem install jekyll
#  - gem install jekyll-paginate
#  - gem install jekyll-git_metadata
  - jekyll build -V -d public
  artifacts:
    paths:
    - public
  only:
  - master
