# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/jekyll
image: ruby:2.3

# build process now happening at netlify: http://netlify.com
# stages:
# - test
# - deploy

pages-build-test:
  stage: test
  script:
  - gem install bundler
  - bundle install
  - rm _posts/*
  - cp _testposts/*.md _posts/
  - jekyll build -d test
#  artifacts:
#    paths:
#    - test
  only:
  - master

pages:
  stage: deploy
  script:
  - gem install bundler
  - bundle install
  - jekyll build -d public
  - cd signal-log
  - gem install bundler
  - bundle install
  - jekyll build -d ../public/signal-log
  - cd -
  artifacts:
    paths:
    - public
  only:
  - master
