source:      .
destination: ./_site
includes:    ./_includes

name: monkinetic weblog
url: http://echoloquation.com/stage

auto: false
exclude:
- fabfile.py
- build
- README.markdown

rdiscount:
    extensions: [smart, autolink]