# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sivy.github.io/" # the base hostname & protocol for your site

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml

# THEME-SPECIFIC CONFIGURATION
theme_data:
  # Meta
  title: Monkinetic
  avatar: sivy_avatar_256.png
  # gravatar: 4fe0ff89158486e907c3a19ded9ac0df
  description: "Steve Ivy's weblog since 1999: XIV Ed." # used by search engines

  # Header and footer text
  header_text: >
   <p>Steve Ivy &mdash; Since 1999 &mdash; XIV Ed.</p>
  footer_text: >
   <h3>Comments</h3>
   <p>
   No, I don't have a comment box. If you'd like to get in touch, I would like to hear 
   your thoughts - send them to steveivy @ gmail.com.
   </p>
   <p>&copy; Copyright Steve Ivy, 1999-2015</p>

  # Icons
  rss: true
  email_address: steveivy@gmail.com  # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "sivy/sivy.github.io"
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "steveivy"
  wordpress:
  youtube:

  # Scripts
  # google_analytics: # Tracking ID, e.g. "UA-000000-01"
  # disqus_shortname:
  # katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PERMALINK
permalink: /:title

# PAGINATION
paginate: 10
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed

# Read Time is a calculator to provide post Estimated Reading Time (ERT) based on word count. Usage is recommended.
readtime:   true
wpm: 200

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
