# JEKYLL
encoding: utf-8

gems:
- jekyll-paginate
- jekyll-auto-image
# - markdown_macros
# - jekyll-git_metadata

# SITE CONFIGURATION
baseurl: "/signal-log" # the subpath of your site, e.g. /blog/
url: "//monkinetic.blog" # the base hostname & protocol for your site

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml

# THEME-SPECIFIC CONFIGURATION
theme_data:
  # Meta
  title: "Este DeStirr: Signal Log"
  avatar: "//i.imgur.com/cLhV1VY.png"
  # gravatar: 4fe0ff89158486e907c3a19ded9ac0df
  description: "Signal Cartel, EvE-Scout Enclave [SC0UT], New Eden cluster, EVE Online"

  # Header and footer text
  header_text: >
   Signal Cartel, EvE-Scout Enclave [SC0UT], New Eden cluster, EVE Online
  footer_text: >
   <h3>Comment Policy</h3>
   <p>
   I don't have comments enabled on this blog. I'd much rather you wrote your own blog post or
   sent me an email instead - steveivy @ gmail.com. You can also hit me up on
   Twitter <a href="https://twitter.com/estedestirr">@estedestirr</a>.
   </p>
   <p>
   <a href="https://twitter.com/intent/tweet?screen_name=estedestirr"
      class="twitter-mention-button" data-text="Hey @estedestirr " data-show-count="false">Tweet to @estedestirr</a>
   <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
   </p>
   <p>&copy; Copyright Steve Ivy, 2017</p>

  # Icons
  rss: true
  twitter: "estedestirr"

  # Scripts
  # google_analytics: # Tracking ID, e.g. "UA-000000-01"
  # disqus_shortname:
  # katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PERMALINK
permalink: /:title.html

# PAGINATION
paginate: 10
paginate_path: "/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
